// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX5E1ZVR13poutYw2FgO6IMbQJ0gDvUPs',
    appId: '1:670788227289:web:532bb04110503c7726aec8',
    messagingSenderId: '670788227289',
    projectId: 'esp8266-322e8',
    authDomain: 'esp8266-322e8.firebaseapp.com',
    databaseURL: 'https://esp8266-322e8-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-322e8.appspot.com',
    measurementId: 'G-3GSVBWJHQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YMRtaSvgTb8zneWFiu5oh9S86GBhHc0',
    appId: '1:670788227289:android:0a44b03ba9c18e2926aec8',
    messagingSenderId: '670788227289',
    projectId: 'esp8266-322e8',
    databaseURL: 'https://esp8266-322e8-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-322e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP3TynoA7lROVFwKvwyaLsDIDVwVJeNSg',
    appId: '1:670788227289:ios:3afdf32741a6aeaf26aec8',
    messagingSenderId: '670788227289',
    projectId: 'esp8266-322e8',
    databaseURL: 'https://esp8266-322e8-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-322e8.appspot.com',
    iosBundleId: 'com.example.esp8266WithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP3TynoA7lROVFwKvwyaLsDIDVwVJeNSg',
    appId: '1:670788227289:ios:b74034f5d145a56526aec8',
    messagingSenderId: '670788227289',
    projectId: 'esp8266-322e8',
    databaseURL: 'https://esp8266-322e8-default-rtdb.firebaseio.com',
    storageBucket: 'esp8266-322e8.appspot.com',
    iosBundleId: 'com.example.esp8266WithFirebase.RunnerTests',
  );
}
